local allStats = T{};
--
allStats.wtype = { order=1, category="Weapons", parent=nil, name="Weapon Type", longName="Weapon Type", desc="", min=0, cap=0, match="", augids=nil };
allStats.dmg = { order=2, category="Weapons", parent=nil, name="DMG", longName="Weapon Damage", desc="", min=0, cap=0, match="", augids=nil };
allStats.delay = { order=3, category="Weapons", parent=nil, name="Delay", longName="Delay", desc="", min=0, cap=0, match="", augids=nil };
--
allStats.shsize = { order=4, category="Shield", parent=nil, name="Size", longName="Shield Size", desc="", min=0, cap=0, match="", augids=nil };
--
allStats.str = { order=4, category="Attributes", parent=nil, name="STR", longName="Strength", desc="", min=0, cap=0, match="(?:STR|All Attr.)(\\+|-)", augids={ 11 }, defsign=nil };
allStats.dex = { order=5, category="Attributes", parent=nil, name="DEX", longName="Dexterity", desc="", min=0, cap=0, match="(?:DEX|All Attr.)(\\+|-)", augids={ 12 }, defsign=nil };
allStats.vit = { order=6, category="Attributes", parent=nil, name="VIT", longName="Vitality", desc="", min=0, cap=0, match="(?:VIT|All Attr.)(\\+|-)", augids={ 13 }, defsign=nil };
allStats.agi = { order=7, category="Attributes", parent=nil, name="AGI", longName="Agility", desc="", min=0, cap=0, match="(?:AGI|All Attr.)(\\+|-)", augids={ 14 }, defsign=nil };
allStats.int = { order=8, category="Attributes", parent=nil, name="INT", longName="Intelligence", desc="", min=0, cap=0, match="(?:INT|All Attr.)(\\+|-)", augids={ 15 }, defsign=nil };
allStats.mnd = { order=9, category="Attributes", parent=nil, name="MND", longName="Mind", desc="", min=0, cap=0, match="(?:MND|All Attr.)(\\+|-)", augids={ 16 }, defsign=nil };
allStats.chr = { order=10, category="Attributes", parent=nil, name="CHR", longName="Charisma", desc="", min=0, cap=0, match="(?:CHR|All Attr.)(\\+|-)", augids={ 17 }, defsign=nil };
--
allStats.hp = { order=11, category="Stats", parent=nil, name="HP", longName="HP", desc="", min=0, cap=0, match="HP(\\+|-)", augids={ 9 }, defsign=nil };
allStats.mp = { order=12, category="Stats", parent=nil, name="MP", longName="MP", desc="", min=0, cap=0, match="MP(\\+|-)", augids={ 10 }, defsign=nil };
allStats.convertsHPMP = { order=13, category="Stats", parent=nil, name="Convert HPMP", longName="Convert HP to MP", desc="", min=0, cap=0, match="Converts (\\d+) HP to MP", augids=nil };
allStats.convertsMPHP = { order=14, category="Stats", parent=nil, name="Convert MPHP", longName="Convert MP to HP", desc="", min=0, cap=0, match="Converts (\\d+) MP to HP", augids=nil };
allStats.acc = { order=15, category="Stats", parent=nil, name="Acc", longName="Accuracy", desc="", min=0, cap=0, match="[^RangedMgic ] ?(?:Accuracy|Acc.)(\\+|-)", augids={ 18 }, defsign=nil };
allStats.atk = { order=16, category="Stats", parent=nil, name="Atk", longName="Attack", desc="", min=0, cap=0, match="[^Ranged ] ?(?:Attack|Atk.)(\\+|-)", augids={ 19 }, defsign=nil };
allStats.racc = { order=17, category="Stats", parent=nil, name="RAcc", longName="Ranged Accuracy", desc="", min=0, cap=0, match="(?:Ranged Accuracy|Ranged Acc.|Rng. Acc.)(\\+|-)", augids={ 20 }, defsign=nil };
allStats.ratk = { order=18, category="Stats", parent=nil, name="RAtk", longName="Ranged Attack", desc="", min=0, cap=0, match="(?:Ranged Attack|Ranged Atk.|Rng. Atk.)(\\+|-)", augids={ 21 }, defsign=nil };
allStats.macc = { order=19, category="Stats", parent=nil, name="MAcc", longName="Magic Accuracy", desc="", min=0, cap=0, match="(?:Magic Accuracy|Magic Acc.|Mag. Acc.)(\\+|-)", augids={ 24 }, defsign=nil };
allStats.mab = { order=20, category="Stats", parent=nil, name="Mab", longName="Magic Attack Bonus", desc="", min=0, cap=0, match="\"Magic Atk\\. Bonus\"(\\+|-)", augids={ 133 }, defsign=nil };
allStats.def = { order=22, category="Stats", parent=nil, name="Def", longName="Defense", desc="", min=0, cap=0, match="DEF:(\\+|-)?", augids={ 23 }, defsign=nil };
allStats.mdb = { order=23, category="Stats", parent=nil, name="MDB", longName="Magic Defense Bonus", desc="", min=0, cap=0, match="(?:\"Magic Def\\. Bonus\"|\"Mag. Def. Bonus\")(\\+|-)", augids={ 134 }, defsign=nil };
allStats.eva = { order=24, category="Stats", parent=nil, name="Eva", longName="Evasion", desc="", min=0, cap=0, match="[^Magic ] ?(?:Evasion|Eva.)(\\+|-)", augids={ 22 }, defsign=nil };
allStats.meva = { order=25, category="Stats", parent=nil, name="MEva", longName="Magic Evasion", desc="", min=0, cap=0, match="(?:Magic Evasion|Magic Eva.|Mag. Eva.)(\\+|-)", augids={ 25 }, defsign=nil };
allStats.mdmg = { order=21, category="Stats", parent=nil, name="MDMG", longName="Magic Damage", desc="", min=0, cap=0, match="Magic Damage(\\+|-)", augids={ 362 }, defsign=nil };
allStats.fireResist = { order=26, category="Stats", parent=nil, name="FIR Resist", longName="Fire Resistance", desc="", min=0, cap=0, match="FireResist(\\+|-)", augids={ 1 }, defsign=nil };
allStats.iceResist = { order=27, category="Stats", parent=nil, name="ICE Resist", longName="Ice Resistance", desc="", min=0, cap=0, match="IceResist(\\+|-)", augids={ 2 }, defsign=nil };
allStats.windResist = { order=28, category="Stats", parent=nil, name="WIN Resist", longName="Wind Resistance", desc="", min=0, cap=0, match="WindResist(\\+|-)", augids={ 3 }, defsign=nil };
allStats.earthResist = { order=29, category="Stats", parent=nil, name="ETH Resist", longName="Earth Resistance", desc="", min=0, cap=0, match="EarthResist(\\+|-)", augids={ 4 }, defsign=nil };
allStats.ltngResist = { order=30, category="Stats", parent=nil, name="LIT Resist", longName="Lightning Resistance", desc="", min=0, cap=0, match="LtngResist(\\+|-)", augids={ 5 }, defsign=nil };
allStats.waterResist = { order=31, category="Stats", parent=nil, name="WTR Resist", longName="Water Resistance", desc="", min=0, cap=0, match="WaterResist(\\+|-)", augids={ 6 }, defsign=nil };
allStats.lightResist = { order=32, category="Stats", parent=nil, name="LGT Resist", longName="Light Resistance", desc="", min=0, cap=0, match="LightResist(\\+|-)", augids={ 7 }, defsign=nil };
allStats.darkResist = { order=33, category="Stats", parent=nil, name="DRK Resist", longName="Dark Resistance", desc="", min=0, cap=0, match="DarkResist(\\+|-)", augids={ 8 }, defsign=nil };
--
allStats.regen = { order=34, category="Utility", parent=nil, name="Regen", longName="Regen", desc="", min=0, cap=0, match="(?:Adds \"Regen\" effect|\"Regen\"(\\+|-))", augids={ 137 }, defsign=nil };
allStats.refresh = { order=35, category="Utility", parent=nil, name="Refresh", longName="Refresh", desc="", min=0, cap=0, match="(?:Adds \"Refresh\" effect|\"Refresh\"(\\+|-))", augids={ 138 }, defsign=nil };
allStats.regain = { order=36, category="Utility", parent=nil, name="Regain", longName="Regain", desc="", min=0, cap=0, match="\"Regain\"(\\+|-)", augids=nil };
allStats.wsd = { order=37, category="Utility", parent=nil, name="WSD", longName="Weaponskill Damage", desc="", min=0, cap=0, match="(?:Increases )?[Ww]eapon skill damage (\\+|-)?", augids={ 327 }, defsign=nil };
allStats.wsa = { order=38, category="Utility", parent=nil, name="WSA", longName="Weaponskill Accuracy", desc="", min=0, cap=0, match="Weapon Skill Accuracy(\\+|-)", augids={ 326 }, defsign=nil };
allStats.scd = { order=39, category="Utility", parent=nil, name="SCD", longName="Skillchain Damage Bonus", desc="", min=0, cap=0, match="\"?Skillchain Bonus\"?(\\+|-)", augids={ 332 }, defsign=nil };
allStats.mbb = { order=40, category="Utility", parent=nil, name="MBB", longName="Magic Burst Bonus", desc="", min=0, cap=40, match="(?:Bonus damage added to magic burst|\"?Magic burst damage\"?) ?(\\+|-)?", augids={ 334, 1285 }, defsign=nil };
allStats.mbbii = { order=41, category="Utility", parent=nil, name="MBBII", longName="Magic Burst Bonus II", desc="", min=0, cap=40, match="(?:\"?Magic burst damage\"? II )(\\+|-)", augids={ 1286 }, defsign=nil };
allStats.mbacc = { order=41, category="Utility", parent=nil, name="MBAcc", longName="Magic Burst Accuracy", desc="", min=0, cap=40, match="(?:Magic burst accuracy)(\\+|-)", augids={ 1287 }, defsign=nil };
allStats.sb = { order=42, category="Utility", parent=nil, name="SB", longName="Subtle Blow", desc="", min=0, cap=50, match="\"Subtle Blow\"(\\+|-)", augids={ 195 }, defsign=nil };
allStats.sbii = { order=43, category="Utility", parent=nil, name="SBII", longName="Subtle Blow II", desc="", min=0, cap=50, match="\"Subtle Blow II\"(\\+|-)", augids={ 1536 }, defsign=nil };
allStats.pdt = { order=44, category="Utility", parent=nil, name="PDT", longName="Physical Damage Taken", desc="", min=0, cap=50, match="(?:Physical damage|Phys\\. dmg\\.) taken (\\+|-)", augids={ 37 }, defsign=nil };
allStats.pdtii = { order=45, category="Utility", parent=nil, name="PDTII", longName="Physical Damage Taken II", desc="", min=0, cap=50, match="(?:Physical damage|Phys\\. dmg\\.) taken II (\\+|-)", augids=nil };
allStats.mdt = { order=46, category="Utility", parent=nil, name="MDT", longName="Magic Damage Taken", desc="", min=0, cap=50, match="Magic damage taken (\\+|-)", augids={ 38 }, defsign=nil };
allStats.mdtii = { order=47, category="Utility", parent=nil, name="MDTII", longName="Magic Damage Taken II", desc="", min=0, cap=50, match="Magic damage taken II (\\+|-)", augids=nil };
allStats.bdt = { order=48, category="Utility", parent=nil, name="BDT", longName="Breath Damage Taken", desc="", min=0, cap=50, match="Breath damage taken (\\+|-)", augids={ 39 }, defsign=nil };
allStats.bdtii = { order=49, category="Utility", parent=nil, name="BDTII", longName="Breath Damage Taken II", desc="", min=0, cap=50, match="Breath damage taken II (\\+|-)", augids=nil };
allStats.dt = { order=50, category="Utility", parent=nil, name="DT", longName="Damage Taken", desc="", min=0, cap=50, match="(?:Damage taken )(\\+|-)", augids={ 41, 55 }, defsign=nil };
allStats.dtii = { order=51, category="Utility", parent=nil, name="DTII", longName="Damage Taken II", desc="", min=0, cap=50, match="(?:Damage taken II )(\\+|-)", augids=nil };
allStats.stp = { order=52, category="Utility", parent=nil, name="STP", longName="Store TP", desc="", min=0, cap=0, match="\"Store TP\"(\\+|-)", augids={ 142 }, defsign=nil };
allStats.dw = { order=53, category="Utility", parent=nil, name="DW", longName="Dual Wield", desc="", min=0, cap=0, match="\"Dual Wield\"(?: effect)?(\\+|-)", augids={ 146 }, defsign=nil };
allStats.dblatk = { order=54, category="Utility", parent=nil, name="Dbl. Atk", longName="Double Attack", desc="", min=0, cap=0, match="(?:Enhances \"Double Attack\" effect|\"Double Attack\"(\\+|-))", augids={ 132, 143 }, defsign=nil };
allStats.tplatk = { order=55, category="Utility", parent=nil, name="Tpl. Atk", longName="Triple Attack", desc="", min=0, cap=0, match="\"Triple Attack\"(\\+|-)", augids={ 144 }, defsign=nil };
allStats.qdatk = { order=56, category="Utility", parent=nil, name="Quad. Atk", longName="Quadruple Attack", desc="", min=0, cap=0, match="\"Quadruple Attack\"[^ ](\\+|-)", augids={ 354 }, defsign=nil };
allStats.dblatkdmg = { order=57, category="Utility", parent=nil, name="Dbl. Atk Dmg", longName="Double Attack Damage", desc="", min=0, cap=0, match="\"Double Attack\" damage(\\+|-)", augids={ 1302 }, defsign=nil };
allStats.tplatkdmg = { order=58, category="Utility", parent=nil, name="Tpl. Atk Dmg", longName="Triple Attack Damage", desc="", min=0, cap=0, match="\"Triple Attack\" damage(\\+|-)", augids={ 1305 }, defsign=nil };
allStats.crit = { order=59, category="Utility", parent=nil, name="Crit", longName="Critical Hit Rate", desc="", min=0, cap=0, match="Critical hit rate (\\+|-)", augids={ 26, 132 }, defsign=nil };
allStats.critdmg = { order=60, category="Utility", parent=nil, name="Crit Dmg", longName="Critical Hit Damage", desc="", min=0, cap=0, match="(?:Increases critical hit damage|Critical hit damage )(\\+|-)", augids={ 328 }, defsign=nil };
allStats.mcrit = { order=61, category="Utility", parent=nil, name="Magic Crit", longName="Magic Critical Hit Rate", desc="", min=0, cap=0, match="Magic critical hit rate [^II] ?(\\+|-)", augids={ 40 }, defsign=nil };
allStats.mcritii = { order=62, category="Utility", parent=nil, name="Magic Crit II", longName="Magic Critical Hit Rate II", desc="", min=0, cap=0, match="Magic critical hit rate II (\\+|-)", augids=nil };
allStats.mcritdmg = { order=63, category="Utility", parent=nil, name="Magic Crit Dmg", longName="Magic Critical Hit Damage", desc="", min=0, cap=0, match="(?:Increases magic critical hit damage|Magic critical hit damage )(\\+|-)", augids={ 335 }, defsign=nil };
allStats.pdl = { order=64, category="Utility", parent=nil, name="PDL", longName="Physical Damage Limit", desc="", min=0, cap=0, match="Physical damage limit (\\+|-)", augids={ 380 }, defsign=nil };
allStats.haste = { order=65, category="Utility", parent=nil, name="Haste", longName="Haste", desc="", min=0, cap=0, match="Haste(\\+|-)", augids={ 32 }, defsign=nil };
allStats.slow = { order=66, category="Utility", parent=nil, name="Slow", longName="Slow", desc="", min=0, cap=0, match="\"Slow\"(\\+|-)", augids={ 33 }, defsign=nil };
allStats.fc = { order=67, category="Utility", parent=nil, name="FC", longName="Fast Cast", desc="", min=0, cap=0, match="(?:Increases \"Fast Cast\" effect|\"Fast Cast\"(\\+|-))", augids={ 140 }, defsign=nil };
allStats.tpbonus = { order=68, category="Utility", parent=nil, name="TP Bonus", longName="TP Bonus", desc="", min=0, cap=0, match="\"?TP Bonus\"?(?! )(\\+|-)?", augids={ 53, 353 }, defsign=nil };
allStats.conservetp = { order=69, category="Utility", parent=nil, name="Conserve TP", longName="Conserve TP", desc="", min=0, cap=0, match="\"Conserve TP\"(\\+|-)", augids={ 333 }, defsign=nil };
allStats.conservemp = { order=70, category="Utility", parent=nil, name="Conserve MP", longName="Conserve MP", desc="", min=0, cap=0, match="\"Conserve MP\"(\\+|-)", augids={ 141 }, defsign=nil };
allStats.encduration = { order=71, category="Utility", parent=nil, name="Enc. Duration", longName="Enhancing Magic Duration", desc="", min=0, cap=0, match="(?:Increases enhancing magic effect duration|Enhancing magic duration )(\\+|-)", augids={ 874, 1248 }, defsign=nil };
allStats.enfduration = { order=72, category="Utility", parent=nil, name="Enf. Duration", longName="Enfeebling Magic Duration", desc="", min=0, cap=0, match="Enfeebling magic duration (\\+|-)", augids={ 872, 1251 }, defsign=nil };
allStats.enfeffect = { order=73, category="Utility", parent=nil, name="Enf. Effect", longName="Enfeebling Magic Effect", desc="", min=0, cap=0, match="(?:Enhances enfeebling magic effect|Enfeebling magic effect )(\\+|-)", augids=nil };
allStats.sird = { order=74, category="Utility", parent=nil, name="SIRD", longName="Spell Interuption Rate Down", desc="", min=0, cap=0, match="Spell interruption rate (?:down )?(\\+|-)?", augids={ 36 }, defsign=-1 };
allStats.block = { order=75, category="Utility", parent=nil, name="Block", longName="Block Rate", desc="", min=0, cap=0, match="Chance of successful block (\\+|-)", augids={ 363 }, defsign=nil };
allStats.ready = { order=76, category="Utility", parent=nil, name="Ready", longName="Ready/Sic Recast", desc="", min=0, cap=0, match="\"Sic\" and \"Ready\" ability delay (\\+|-)", augids={ 336 }, defsign=nil };
allStats.bpdelay = { order=77, category="Utility", parent=nil, name="BP Delay", longName="Blood Pact Ability Delay", desc="", min=0, cap=15, match="\"?Blood Pact\"? (?:recast time|ability delay) (\\+|-)", augids={ 320 }, defsign=nil };
allStats.bpdelayii = { order=78, category="Utility", parent=nil, name="BP Delay II", longName="Blood Pact Ability Delay II", desc="", min=0, cap=15, match="\"?Blood Pact\"? (?:recast time|ability delay) II (\\+|-)", augids={ 366 }, defsign=nil };
allStats.resistallstat = { order=79, category="Utility", parent=nil, name="Resist All Status", longName="Resistance to all status ailments", desc="", min=0, cap=0, match="all status ailments ?(\\+|-)", augids=nil };
allStats.resistallele = { order=80, category="Utility", parent=nil, name="Resist All Element", longName="Resist all elements", desc="", min=0, cap=0, match="(?:Resist|Res.) all (?:elements|ele.) (\\+|-)", augids=nil };
allStats.enmity = { order=81, category="Utility", parent=nil, name="Enmity", longName="Enmity", desc="", min=0, cap=0, match="Enmity(\\+|-)", augids={ 29 }, defsign=nil };
allStats.bpd = { order=138, category="Utility", parent="petbpd", name="BPD", longName="Blood Pact Damage", desc="", min=0, cap=0, match="\"Blood Pact\"(?: ability)? damage (\\+|-)", augids={ 369 }, defsign=nil };
--
allStats.skh2h = { order=83, category="Skills", parent=nil, name="H2H", longName="Hand-to-Hand Skill", desc="", min=0, cap=0, match="(?:Hand-to-Hand skill|Combat skills) (\\+|-)", augids={ 256 }, defsign=nil };
allStats.skdagger = { order=84, category="Skills", parent=nil, name="Dagger", longName="Dagger Skill", desc="", min=0, cap=0, match="(?:Dagger skill|Combat skills) (\\+|-)", augids={ 257 }, defsign=nil };
allStats.sksword = { order=85, category="Skills", parent=nil, name="Sword", longName="Sword Skill", desc="", min=0, cap=0, match="(?:[^Great ]Sword skill|Combat skills) (\\+|-)", augids={ 258 }, defsign=nil };
allStats.skgreatsword = { order=86, category="Skills", parent=nil, name="Great Sword", longName="Great Sword Skill", desc="", min=0, cap=0, match="(?:Great Sword skill|Combat skills) (\\+|-)", augids={ 259 }, defsign=nil };
allStats.skaxe = { order=87, category="Skills", parent=nil, name="Axe", longName="Axe Skill", desc="", min=0, cap=0, match="(?:[^Great ]Axe skill|Combat skills) (\\+|-)", augids={ 260 }, defsign=nil };
allStats.skgreataxe = { order=88, category="Skills", parent=nil, name="Great Axe", longName="Great Axe Skill", desc="", min=0, cap=0, match="(?:Great Axe skill|Combat skills) (\\+|-)", augids={ 261 }, defsign=nil };
allStats.skscythe = { order=89, category="Skills", parent=nil, name="Scythe", longName="Scythe Skill", desc="", min=0, cap=0, match="(?:Scythe skill|Combat skills) (\\+|-)", augids={ 262 }, defsign=nil };
allStats.skpolearm = { order=90, category="Skills", parent=nil, name="Polearm", longName="Polearm Skill", desc="", min=0, cap=0, match="(?:Polearm skill|Combat skills) (\\+|-)", augids={ 263 }, defsign=nil };
allStats.skkatana = { order=91, category="Skills", parent=nil, name="Katana", longName="Katana Skill", desc="", min=0, cap=0, match="(?:[^Great ]Katana skill|Combat skills) (\\+|-)", augids={ 264 }, defsign=nil };
allStats.skgreatkatana = { order=92, category="Skills", parent=nil, name="Great Katana", longName="Great Katana Skill", desc="", min=0, cap=0, match="(?:Great Katana skill|Combat skills) (\\+|-)", augids={ 265 }, defsign=nil };
allStats.skclub = { order=93, category="Skills", parent=nil, name="Club", longName="Club Skill", desc="", min=0, cap=0, match="(?:Club skill|Combat skills) (\\+|-)", augids={ 266 }, defsign=nil };
allStats.skstaff = { order=94, category="Skills", parent=nil, name="Staff", longName="Staff Skill", desc="", min=0, cap=0, match="(?:Staff skill|Combat skills) (\\+|-)", augids={ 267 }, defsign=nil };
allStats.skarchery = { order=95, category="Skills", parent=nil, name="Archery", longName="Archery Skill", desc="", min=0, cap=0, match="(?:Archery skill|Combat skills) (\\+|-)", augids={ 280 }, defsign=nil };
allStats.skmarks = { order=96, category="Skills", parent=nil, name="Marksmanship", longName="Marksmanship Skill", desc="", min=0, cap=0, match="(?:Marksmanship skill|Combat skills) (\\+|-)", augids={ 281 }, defsign=nil };
allStats.skthrow = { order=97, category="Skills", parent=nil, name="Throwing", longName="Throwing Skill", desc="", min=0, cap=0, match="(?:Throwing skill|Combat skills) (\\+|-)", augids={ 282 }, defsign=nil };
allStats.skguard = { order=98, category="Skills", parent=nil, name="Guard", longName="Guarding Skill", desc="", min=0, cap=0, match="(?:Guarding skill|Combat skills) (\\+|-)", augids=nil };
allStats.skeva = { order=99, category="Skills", parent=nil, name="Evasion", longName="Evasion Skill", desc="", min=0, cap=0, match="(?:Evasion skill|Combat skills) (\\+|-)", augids=nil };
allStats.skshield = { order=100, category="Skills", parent=nil, name="Shield", longName="Shield Skill", desc="", min=0, cap=0, match="(?:Shield skill|Combat skills) (\\+|-)", augids={ 285 }, defsign=nil };
allStats.skparry = { order=101, category="Skills", parent=nil, name="Parry", longName="Parrying Skill", desc="", min=0, cap=0, match="(?:Parrying skill|Combat skills) (\\+|-)", augids={ 286 }, defsign=nil };
allStats.skdivine = { order=102, category="Skills", parent=nil, name="Divine", longName="Divine Magic Skill", desc="", min=0, cap=0, match="(?:Divine magic skill|[Mm]agic skills) (\\+|-)", augids={ 287 }, defsign=nil };
allStats.skhealing = { order=103, category="Skills", parent=nil, name="Healing", longName="Healing Magic Skill", desc="", min=0, cap=0, match="(?:Healing magic skill|[Mm]agic skills) (\\+|-)", augids={ 288 }, defsign=nil };
allStats.skenhancing = { order=104, category="Skills", parent=nil, name="Enhancing", longName="Enhancing Magic Skill", desc="", min=0, cap=0, match="(?:Enhancing magic skill|[Mm]agic skills) (\\+|-)", augids={ 289 }, defsign=nil };
allStats.skenfeebling = { order=105, category="Skills", parent=nil, name="Enfeebling", longName="Enfeebling Magic Skill", desc="", min=0, cap=0, match="(?:Enfeebling magic skill|[Mm]agic skills) (\\+|-)", augids={ 290 }, defsign=nil };
allStats.skelemental = { order=106, category="Skills", parent=nil, name="Elemental", longName="Elemental Magic Skill", desc="", min=0, cap=0, match="(?:Elemental magic skill|[Mm]agic skills) (\\+|-)", augids={ 291 }, defsign=nil };
allStats.skdark = { order=107, category="Skills", parent=nil, name="Dark", longName="Dark Magic Skill", desc="", min=0, cap=0, match="(?:Dark magic skill|[Mm]agic skills) (\\+|-)", augids={ 292 }, defsign=nil };
allStats.sksummon = { order=108, category="Skills", parent=nil, name="Summoning", longName="Simmoning Magic Skill", desc="", min=0, cap=0, match="(?:Summoning magic skill|[Mm]agic skills) (\\+|-)", augids={ 293 }, defsign=nil };
allStats.skninjutsu = { order=109, category="Skills", parent=nil, name="Ninjutsu", longName="Ninjutsu Skill", desc="", min=0, cap=0, match="(?:Ninjutsu skill|[Mm]agic skills) (\\+|-)", augids={ 294 }, defsign=nil };
allStats.sksinging = { order=110, category="Skills", parent=nil, name="Singing", longName="Singing Skill", desc="", min=0, cap=0, match="(?:Singing skill|[Mm]agic skills) (\\+|-)", augids={ 295 }, defsign=nil };
allStats.skstringinstr = { order=111, category="Skills", parent=nil, name="String", longName="String Instrument Skill", desc="", min=0, cap=0, match="(?:String instrument skill|[Mm]agic skills) (\\+|-)", augids={ 296 }, defsign=nil };
allStats.skwindinstr = { order=112, category="Skills", parent=nil, name="Wind", longName="Wind Instrument Skill", desc="", min=0, cap=0, match="(?:Wind instrument skill|[Mm]agic skills) (\\+|-)", augids={ 297 }, defsign=nil };
allStats.skblue = { order=113, category="Skills", parent=nil, name="Blue Magic", longName="Blue Magic Skill", desc="", min=0, cap=0, match="(?:Blue magic skill|[Mm]agic skills) (\\+|-)", augids={ 298 }, defsign=nil };
allStats.skgeo = { order=114, category="Skills", parent=nil, name="Geomancy", longName="Geomancy Skill", desc="", min=0, cap=0, match="(?:Geomancy skill|[Mm]agic skills) (\\+|-)", augids={ 299 }, defsign=nil };
allStats.skhandbell = { order=115, category="Skills", parent=nil, name="Handbell", longName="Handbell Skill", desc="", min=0, cap=0, match="(?:Handbell skill|[Mm]agic skills) (\\+|-)", augids={ 300 }, defsign=nil };
--
allStats.th = { order=1, category="Traits", parent=nil, name="TH", longName="Treasure Hunter", desc="Increases drops from mobs", min=0, cap=0, match="\"Treasure Hunter\"(\\+|-)", augids={ 147 }, defsign=nil };
allStats.stoutservant = { order=2, category="Traits", parent=nil, name="Stout Servant", longName="Stout Servant", desc="Reduces damage taken for pet", min=0, cap=0, match="\"Stout Servant\"(\\+)", augids=nil, defsign=nil };
allStats.amorphkiller = { order=3, category="Traits", parent=nil, name="Amorph Killer", longName="Amorph Killer", desc="", min=0, cap=0, match="(?:\"Amorph Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.aquankiller = { order=4, category="Traits", parent=nil, name="Aquan Killer", longName="Aquan Killer", desc="", min=0, cap=0, match="(?:\"Aquan Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.arcanakiller = { order=5, category="Traits", parent=nil, name="Arcana Killer", longName="Arcana Killer", desc="", min=0, cap=0, match="(?:\"Arcana Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.beastkiller = { order=6, category="Traits", parent=nil, name="Beast Killer", longName="Beast Killer", desc="", min=0, cap=0, match="(?:\"Beast Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.birdkiller = { order=7, category="Traits", parent=nil, name="Bird Killer", longName="Bird Killer", desc="", min=0, cap=0, match="(?:\"Bird Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.demonkiller = { order=8, category="Traits", parent=nil, name="Demon Killer", longName="Demon Killer", desc="", min=0, cap=0, match="(?:\"Demon Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.dragonkiller = { order=9, category="Traits", parent=nil, name="Dragon Killer", longName="Dragon Killer", desc="", min=0, cap=0, match="(?:\"Dragon Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.lizardkiller = { order=10, category="Traits", parent=nil, name="Lizard Killer", longName="Lizard Killer", desc="", min=0, cap=0, match="(?:\"Lizard Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.plantoidkiller = { order=11, category="Traits", parent=nil, name="Plantoid Killer", longName="Plantoid Killer", desc="", min=0, cap=0, match="(?:\"Plantoid Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.undeadkiller = { order=12, category="Traits", parent=nil, name="Undead Killer", longName="Undead Killer", desc="", min=0, cap=0, match="(?:\"Undead Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
allStats.verminkiller = { order=13, category="Traits", parent=nil, name="Vermin Killer", longName="Vermin Killer", desc="", min=0, cap=0, match="(?:\"Vermin Killer\"|\"Killer\" effects)(\\+|-)?", augids=nil, defsign=nil };
--
allStats.uphalanx = { order=1, category="Unique", parent=nil, name="Phalanx+", longName="Phalanx Received", desc="", min=0, cap=0, match="\"Phalanx\" received (\\+|-)", augids={ 368 } };
allStats.usictpbonus = { order=2, category="Unique", parent="pettpbonus", name="Sic/Ready TP Bonus", longName="\"Sic\"/\"Ready\" TP Bonus", desc="", min=0, cap=0, match="(?:Enhances \"Sic\" and \"Ready\" effect|\"Sic\" TP Bonus|\"Ready\" TP Bonus) (\\+|-)?", augids=nil };
--
allStats.petstr = { order=116, category="Pet: Attributes", parent=nil, name="STR", longName="Strength", desc="", min=0, cap=0, match=allStats.str.match, augids={ 11 }, defsign=nil };
allStats.petdex = { order=117, category="Pet: Attributes", parent=nil, name="DEX", longName="Dexterity", desc="", min=0, cap=0, match=allStats.dex.match, augids={ 12 }, defsign=nil };
allStats.petvit = { order=118, category="Pet: Attributes", parent=nil, name="VIT", longName="Vitality", desc="", min=0, cap=0, match=allStats.vit.match, augids={ 13 }, defsign=nil };
allStats.petagi = { order=119, category="Pet: Attributes", parent=nil, name="AGI", longName="Agility", desc="", min=0, cap=0, match=allStats.agi.match, augids={ 14 }, defsign=nil };
allStats.petint = { order=120, category="Pet: Attributes", parent=nil, name="INT", longName="Intelligence", desc="", min=0, cap=0, match=allStats.int.match, augids={ 15 }, defsign=nil };
allStats.petmnd = { order=121, category="Pet: Attributes", parent=nil, name="MND", longName="Mind", desc="", min=0, cap=0, match=allStats.mnd.match, augids={ 16 }, defsign=nil };
allStats.petchr = { order=122, category="Pet: Attributes", parent=nil, name="CHR", longName="Charisma", desc="", min=0, cap=0, match=allStats.chr.match, augids={ 17 }, defsign=nil };
--
allStats.pethp = { order=123, category="Pet: Stats", parent=nil, name="HP", longName="HP", desc="", min=0, cap=0, match=allStats.hp.match, augids={ 9 }, defsign=nil };
allStats.petmp = { order=124, category="Pet: Stats", parent=nil, name="MP", longName="MP", desc="", min=0, cap=0, match=allStats.mp.match, augids={ 10 }, defsign=nil };
allStats.petatk = { order=125, category="Pet: Stats", parent=nil, name="Atk", longName="Attack", desc="", min=0, cap=0, match=allStats.atk.match, augids={ 19 }, defsign=nil };
allStats.petacc = { order=126, category="Pet: Stats", parent=nil, name="Acc", longName="Accuracy", desc="", min=0, cap=0, match=allStats.acc.match, augids={ 18 }, defsign=nil };
allStats.petratk = { order=127, category="Pet: Stats", parent=nil, name="RAtk", longName="Ranged Attack", desc="", min=0, cap=0, match=allStats.ratk.match, augids={ 21 }, defsign=nil };
allStats.petracc = { order=128, category="Pet: Stats", parent=nil, name="RAcc", longName="Ranged Accuracy", desc="", min=0, cap=0, match=allStats.racc.match, augids={ 20 }, defsign=nil };
allStats.petmab = { order=129, category="Pet: Stats", parent=nil, name="Mab", longName="Magic Attack Bonus", desc="", min=0, cap=0, match=allStats.mab.match, augids={ 133 }, defsign=nil };
allStats.petmacc = { order=130, category="Pet: Stats", parent=nil, name="MAcc", longName="Magic Accuracy", desc="", min=0, cap=0, match=allStats.macc.match, augids={ 24 }, defsign=nil };
allStats.petdef = { order=131, category="Pet: Stats", parent=nil, name="Def", longName="Defense", desc="", min=0, cap=0, match=allStats.def.match, augids={ 23 }, defsign=nil };
allStats.petmdb = { order=132, category="Pet: Stats", parent=nil, name="MDB", longName="Magic Defense Bonus", desc="", min=0, cap=0, match=allStats.mdb.match, augids={ 134 }, defsign=nil };
allStats.peteva = { order=133, category="Pet: Stats", parent=nil, name="Eva", longName="Evasion", desc="", min=0, cap=0, match=allStats.meva.match, augids={ 22 }, defsign=nil };
allStats.petmeva = { order=134, category="Pet: Stats", parent=nil, name="MEva", longName="Magic Evasion", desc="", min=0, cap=0, match=allStats.meva.match, augids={ 25 }, defsign=nil };
--
allStats.petregen = { order=135, category="Pet: Utility", parent=nil, name="Regen", longName="Regen", desc="", min=0, cap=0, match=allStats.regen.match, augids={ 137 }, defsign=nil };
allStats.petrefresh = { order=136, category="Pet: Utility", parent=nil, name="Refresh", longName="Refresh", desc="", min=0, cap=0, match=allStats.refresh.match, augids={ 138 }, defsign=nil };
allStats.petdmg = { order=137, category="Pet: Utility", parent=nil, name="Pet Dmg", longName="Damage", desc="", min=0, cap=0, match="Pet melee attack DMG(\\+|-)", augids={ 47 }, defsign=nil };
allStats.petbpd = { order=138, category="Pet: Utility", parent=nil, name="BPD", longName="Blood Pact Damage", desc="", min=0, cap=0, match=allStats.bpd.match, augids={ 369 }, defsign=nil };
allStats.petdblatk = { order=139, category="Pet: Utility", parent=nil, name="Pet Dbl. Atk", longName="Double Attack", desc="", min=0, cap=0, match=allStats.dblatk.match, augids={ 132, 143 }, defsign=nil };
allStats.petcrit = { order=140, category="Pet: Utility", parent=nil, name="Crit", longName="Critical Hit Rate", desc="", min=0, cap=0, match=allStats.crit.match, augids={ 26, 132 }, defsign=nil };
allStats.petwsd = { order=141, category="Pet: Utility", parent=nil, name="WSD", longName="Weaponskill/Special Attack Damage", desc="", min=0, cap=0, match="Weapon skill damage (\\+|-)", augids={ 327, 1314 }, defsign=nil };
allStats.pethaste = { order=142, category="Pet: Utility", parent=nil, name="Haste", longName="Haste", desc="", min=0, cap=0, match=allStats.haste.match, augids={ 32 }, defsign=nil };
allStats.petpdt = { order=143, category="Pet: Utility", parent=nil, name="PDT", longName="Physical Damage Taken", desc="", min=0, cap=50, match=allStats.pdt.match, augids={ 37 }, defsign=nil };
allStats.petpdtii = { order=144, category="Pet: Utility", parent=nil, name="PDTII", longName="Physical Damage Taken II", desc="", min=0, cap=50, match=allStats.pdtii.match, augids=nil };
allStats.petmdt = { order=145, category="Pet: Utility", parent=nil, name="MDT", longName="Magic Damage Taken", desc="", min=0, cap=50, match=allStats.mdt.match, augids={ 38 }, defsign=nil };
allStats.petmdtii = { order=146, category="Pet: Utility", parent=nil, name="MDTII", longName="Magic Damage Taken II", desc="", min=0, cap=50, match=allStats.mdtii.match, augids=nil };
allStats.petbdt = { order=147, category="Pet: Utility", parent=nil, name="BDT", longName="Breath Damage Taken", desc="", min=0, cap=50, match=allStats.bdt.match, augids={ 39 }, defsign=nil };
allStats.petbdtii = { order=148, category="Pet: Utility", parent=nil, name="BDTII", longName="Breath Damage Taken II", desc="", min=0, cap=50, match=allStats.bdtii.match, augids=nil };
allStats.petdt = { order=149, category="Pet: Utility", parent=nil, name="DT", longName="Damage Taken", desc="", min=0, cap=50, match=allStats.dt.match, augids={ 41, 55 }, defsign=nil };
allStats.petdtii = { order=150, category="Pet: Utility", parent=nil, name="DTII", longName="Damage Taken II", desc="", min=0, cap=50, match=allStats.dtii.match, augids=nil };
allStats.petstp = { order=151, category="Pet: Utility", parent=nil, name="STP", longName="Store TP", desc="", min=0, cap=0, match=allStats.stp.match, augids={ 142 }, defsign=nil };
allStats.petsb = { order=152, category="Pet: Utility", parent=nil, name="SB", longName="Subtle Blow", desc="", min=0, cap=50, match=allStats.sb.match, augids={ 195 }, defsign=nil };
allStats.petblvl = { order=153, category="Pet: Utility", parent=nil, name="Base Level", longName="Base Level", desc="", min=100, cap=0, match="Lv\\.?( )?", augids=nil };
allStats.petlvl = { order=154, category="Pet: Utility", parent=nil, name="Level", longName="Level", desc="", min=0, cap=0, match="Lv\\.? ?(\\+|-)", augids=nil };
allStats.pettpbonus = { order=155, category="Pet: Utility", parent=nil, name="TP Bonus", longName="TP Bonus", desc="", min=0, cap=0, match=allStats.tpbonus.match, augids={ 53, 353 }, defsign=nil };
--
allStats.petmelee = { order=156, category="Pet: Skills", parent=nil, name="Melee", longName="Automaton: Melee Skill", desc="", min=0, cap=0, match="(?:Melee skill|All skills|Skill|combat skill|skill effects)(\\+|-)?", augids={ 277 }, defsign=nil };
allStats.petranged = { order=157, category="Pet: Skills", parent=nil, name="Ranged", longName="Automaton: Ranged Skill", desc="", min=0, cap=0, match="(?:Ranged skill|All skills|Skill|combat skill|skill effects)(\\+|-)?", augids={ 278 }, defsign=nil };
allStats.petmagic = { order=158, category="Pet: Skills", parent=nil, name="Magic", longName="Automaton: Magic Skill", desc="", min=0, cap=0, match="(?:Magic skill|All skills|Skill|combat skill|skill effects)(\\+|-)?", augids={ 279 }, defsign=nil };

return allStats;